# Settings <https://pnpm.io/settings>

## Dependency Resolution

trustPolicy: no-downgrade
trustPolicyExclude:
  - semver@6.3.1
  - chokidar@4.0.3
blockExoticSubdeps: true

## Dependency Hoisting Settings

publicHoistPattern:
  - 'eslint'
  - 'markuplint'
  - 'stylelint'

## Build Settings

strictDepBuilds: true
