# Settings <https://pnpm.io/settings>

## Dependency Resolution

trustPolicy: no-downgrade
blockExoticSubdeps: true

## Dependency Hoisting Settings

publicHoistPattern:
  - 'eslint'
  - 'markuplint'
  - 'stylelint'

## Build Settings

strictDepBuilds: true
