name: js-lint
on:
  pull_request:
    branches:
      - main
    paths:
      - 'public/**/*.js'
      - 'public/**/*.html'
      - 'eslint.config.js'
      - 'package.json'
  push:
    branches:
      - main
    paths:
      - 'public/**/*.js'
      - 'public/**/*.html'
      - 'eslint.config.js'
      - 'package.json'
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-node@v4
        with:
          node-version: '20'
      - run: npm ci
      - run: npm run js-lint
